-- TODOS COMITADOS

CREATE PROCEDURE EDITAR_OPCIONAL
@ID INT, @DESC VARCHAR(50)
AS
BEGIN 
	UPDATE OPCIONAL SET OPCDESCR = @DESC
	WHERE OPCID = @ID
END
--____________________________________________________________________________
CREATE PROCEDURE EDITAR_CARRO
@ID INT, @MODELO VARCHAR(30), @MARCA VARCHAR(20), @COR VARCHAR(30), 
@COMBU VARCHAR(20), @TIPO VARCHAR(20), @ANO VARCHAR(20)
AS
BEGIN 
	UPDATE CARRO SET CARMODEL = @MODELO, CARMARCA = @MARCA, CARCOR = @COR,
			CARCOMBU = @COMBU, CARTIPO = @TIPO, CARANO = @ANO
	WHERE CARID = @ID
END
--____________________________________________________________________________
CREATE PROCEDURE EDITAR_LOGIN
@USER INT, @SENHA VARCHAR(20)
AS
BEGIN 
	UPDATE LOGIN_VENDEDOR SET LOGSENHA = @SENHA
	WHERE LOGUSUAR = @USER
END
--____________________________________________________________________________
CREATE PROCEDURE EDITAR_CLIENTE
@CPF VARCHAR(75), @NOME VARCHAR(75), @ENDER VARCHAR(75),
@CIDADE VARCHAR(30), @TELEFONE VARCHAR(15), @DATA DATE
AS
BEGIN 
	UPDATE CLIENTE SET CLINOME = @NOME, CLIENDER = @ENDER,
		CLICIDAD = @CIDADE, CLITELEF = @TELEFONE, CLIDATAN = @DATA
	WHERE CLICPF = @CPF
END
--_____________________________________________________________________________

