create database CONCESSIONARIA
USE CONCESSIONARIA

CREATE TABLE OPCIONAL(
	OPCID INT CONSTRAINT PK_OPC PRIMARY KEY IDENTITY(1,1),
	OPCDESCR VARCHAR(50) NOT NULL
	)

CREATE TABLE CARRO (
	CARID INT CONSTRAINT PK_CAR PRIMARY KEY IDENTITY(1,1),
	CARMODEL VARCHAR(40) NOT NULL,
	CARMARCA VARCHAR(30) NOT NULL,
	CARCOR VARCHAR(20) NOT NULL,
	CARCOMBU VARCHAR(30),
	CARTIPO VARCHAR(20),
	CARANO VARCHAR(4) NOT NULL
	)

CREATE TABLE CARRO_OPCIONAL(
	CARID INT CONSTRAINT FK_CO1 FOREIGN KEY REFERENCES CARRO(CARID),
	OPCID INT CONSTRAINT FK_CO2 FOREIGN KEY REFERENCES OPCIONAL(OPCID)
		CONSTRAINT PK_C0 PRIMARY KEY (CARID, OPCID)
	)

CREATE TABLE LOGIN_VENDEDOR (
	LOGUSUAR VARCHAR(12) NOT NULL CONSTRAINT PK_LV PRIMARY KEY,
	LOGSENHA VARCHAR(12) NOT NULL
	)

CREATE TABLE CLIENTE (
	CLICPF VARCHAR(12) NOT NULL CONSTRAINT FK_CLI PRIMARY KEY,
	CLINOME VARCHAR(75) NOT NULL,
	CLIENDER VARCHAR(75) NOT NULL,
	CLICIDAD VARCHAR(75) DEFAULT 'FRANCA',
	CLIDATAN DATE,
	CLITELEF VARCHAR(12)
	)

CREATE TABLE VENDA(
	CLICPF VARCHAR(12) NOT NULL CONSTRAINT FK_VEN1 FOREIGN KEY REFERENCES CLIENTE(CLICPF),
	CARID INT NOT NULL CONSTRAINT FK_VEN2 FOREIGN KEY REFERENCES CARRO(CARID),
	VENVALOR MONEY,
	VENDATAV DATE
		CONSTRAINT PK_VEN PRIMARY KEY (CLICPF, CARID)
	)
--_________________________________________________________________

