--TODOS COMITADOS
ALTER PROCEDURE INSERIR_OPCIONAL
@OPCDESCR VARCHAR(50)
AS
BEGIN 
	INSERT INTO OPCIONAL VALUES (@OPCDESCR)
END
--_____________________________________________________________________
ALTER PROCEDURE INSERIR_CARRO
@CARPLACA VARCHAR(8), @CARMODEL VARCHAR(50), @CARMARCA VARCHAR(20), @CARANO VARCHAR(20), 
@CARTIPO VARCHAR(20), @CARCOMBU VARCHAR(30), @CARCOR VARCHAR(30)
AS
BEGIN 
	INSERT INTO CARRO (CARPLACA, CARMODEL, CARMARCA, CARANO, CARTIPO, CARCOMBU, CARCOR)
	VALUES (@CARPLACA, @CARMODEL, @CARMARCA, @CARANO, @CARTIPO, @CARCOMBU, @CARCOR)
END
--_____________________________________________________________________
ALTER PROCEDURE INSERIR_CARRO_OPCIONAL
@CARPLACA VARCHAR(8), @OPCID INT
AS BEGIN
	INSERT INTO CARRO_OPCIONAL(CARPLACA, OPCID) VALUES(@CARPLACA, @OPCID)
END
SELECT * FROM CARRO_OPCIONAL
--_____________________________________________________________________
ALTER PROCEDURE INSERIR_CLIENTE
@CLICPF VARCHAR(12), @CLINOME VARCHAR(75), @CLIENDER VARCHAR(75), 
@CLITELEF VARCHAR(13),@CLIDATAN DATE, @CLICIDAD VARCHAR(30)
AS
BEGIN 
	INSERT INTO CLIENTE(CLICPF, CLINOME, CLIENDER, CLITELEF, CLIDATAN, CLICIDAD)
	VALUES (@CLICPF, @CLINOME, @CLIENDER, @CLITELEF, @CLIDATAN, @CLICIDAD)
END
--________________________________________________________________________
ALTER PROCEDURE INSERIR_LOGIN
@LOGUSER VARCHAR(12), @LOGSENHA VARCHAR(12)
AS
BEGIN 
	INSERT INTO LOGIN_VENDEDOR(LOGUSUAR, LOGSENHA)
	VALUES (@LOGUSER, @LOGSENHA)
END
--____________________________________________________________________________
ALTER PROCEDURE INSERIR_VENDA
@CLICPF INT, @CARPLACA INT, @VENVALOR MONEY, @VENDATAV DATE
AS
BEGIN 
	INSERT INTO VENDA (CLICPF, CARPLACA, VENVALOR, VENDATAV)
	VALUES (@CLICPF, @CARPLACA, @VENVALOR, @VENDATAV)
END
