create database CONCESSIONARIA
USE CONCESSIONARIA
--coment
CREATE TABLE OPCIONAL(
	OPCID INT CONSTRAINT PK_OPC PRIMARY KEY IDENTITY(1,1),
	OPCDESCR VARCHAR(50) NOT NULL
	)

CREATE TABLE CARRO (
	CARPLACA VARCHAR(8) CONSTRAINT PK_CAR PRIMARY KEY,
	CARMODEL VARCHAR(40) NOT NULL,
	CARMARCA VARCHAR(30) NOT NULL,
	CARCOR VARCHAR(20) NOT NULL,
	CARCOMBU VARCHAR(30),
	CARTIPO VARCHAR(20),
	CARANO VARCHAR(10) NOT NULL,
	CARSTATUS INT DEFAULT(0)
	)

SELECT * FROM CARRO_OPCIONAL
CREATE TABLE CARRO_OPCIONAL(
	CARPLACA VARCHAR(8) CONSTRAINT FK_CO1 FOREIGN KEY REFERENCES CARRO(CARPLACA),
	OPCID INT CONSTRAINT FK_CO2 FOREIGN KEY REFERENCES OPCIONAL(OPCID)
		CONSTRAINT PK_C0 PRIMARY KEY (CARPLACA, OPCID)
	)

CREATE TABLE LOGIN_VENDEDOR (
	LOGUSUAR VARCHAR(12) NOT NULL CONSTRAINT PK_LV PRIMARY KEY,
	LOGSENHA VARCHAR(12) NOT NULL
	)

CREATE TABLE CLIENTE (
	CLICPF VARCHAR(12) NOT NULL CONSTRAINT FK_CLI PRIMARY KEY,
	CLINOME VARCHAR(75) NOT NULL,
	CLIENDER VARCHAR(75) NOT NULL,
	CLICIDAD VARCHAR(75) DEFAULT 'FRANCA',
	CLIDATAN DATE,
	CLITELEF VARCHAR(12)
	)

CREATE TABLE VENDA(
	VENID INT NOT NULL CONSTRAINT PK_VEN PRIMARY KEY IDENTITY(1,1),
	CLICPF VARCHAR(12) NOT NULL CONSTRAINT FK_VEN1 FOREIGN KEY REFERENCES CLIENTE(CLICPF),
	CARPLACA VARCHAR(9) CONSTRAINT FK_VEN2 FOREIGN KEY REFERENCES CARRO(CARPLACA),
	VENVALOR MONEY,
	VENDATAV DATE		
	)
--_________________________________________________________________

CREATE TRIGGER ALTERA_STATUS_CARRO
ON VENDA
FOR INSERT
AS 
BEGIN
	DECLARE @CARPLACA VARCHAR(8)
	
	SELECT @CARPLACA = CARPLACA FROM INSERTED

	UPDATE CARRO SET CARSTATUS = 1
	WHERE CARPLACA = @CARPLACA
END

