-- TODOS COMITADOS

CREATE PROCEDURE EDITAR_OPCIONAL
	@OPCID INT, 
	@OPCDESCR VARCHAR(50)
	
	AS
	BEGIN 
		UPDATE OPCIONAL SET OPCDESCR = @OPCDESCR
		WHERE OPCID = @OPCID
	END
--____________________________________________________________________________
ALTER PROCEDURE EDITAR_CARRO
	@CARPLACA VARCHAR(8), 
	@CARMODEL VARCHAR(30), 
	@CARMARCA VARCHAR(20), 
	@CARCOR VARCHAR(30), 
	@CARCOMBU VARCHAR(20) = NULL, 
	@CARTIPO VARCHAR(20) = NULL, 
	@CARANO VARCHAR(20)
	
	AS
	BEGIN 
		UPDATE CARRO 
			SET CARMODEL = @CARMODEL, 
				CARMARCA = @CARMARCA, 
				CARCOR	= @CARCOR,
				CARCOMBU = @CARCOMBU, 
				CARTIPO = @CARTIPO, 
				CARANO = @CARANO
		WHERE CARPLACA = @CARPLACA
	END
--____________________________________________________________________________
CREATE PROCEDURE EDITAR_LOGIN
	@LOGUSER VARCHAR(12), 
	@LOGSENHA VARCHAR(12)

	AS
	BEGIN 
		UPDATE LOGIN_VENDEDOR 
			SET LOGSENHA = @LOGSENHA
		WHERE LOGUSUAR = @LOGUSER
	END
--____________________________________________________________________________
ALTER PROCEDURE EDITAR_CLIENTE
	@CLICPF VARCHAR(75), 
	@CLINOME VARCHAR(75),
	@CLIENDER VARCHAR(75),
	@CLICIDAD VARCHAR(30) = 'FRANCA', 
	@CLITELEF VARCHAR(15) = 'NULL', 
	@CLIDATAN DATE
	
	AS
	BEGIN 
		UPDATE CLIENTE 
			SET CLINOME = @CLINOME, 
				CLIENDER = @CLIENDER,
				CLICIDAD = @CLICIDAD, 
				CLITELEF = @CLITELEF, 
				CLIDATAN = @CLIDATAN
		WHERE CLICPF = @CLICPF
	END
--_____________________________________________________________________________

