-- COMITADOS
CREATE PROCEDURE LISTAR_OPCIONAL_ID
@OPCID INT
AS
BEGIN 
	SELECT * FROM OPCIONAL
	WHERE OPCID = @OPCID
END
--_________________________________________________________________
CREATE PROCEDURE LISTAR_CARRO_ID
@CARPLACA VARCHAR(8)
AS
BEGIN 
	SELECT * FROM CARRO
	WHERE CARPLACA = @CARPLACA
END
--_________________________________________________________________
CREATE PROCEDURE LISTAR_CARRO_OPCIONAL_ID
@CARPLACA VARCHAR(8)
AS
BEGIN	
	SELECT O.OPCID, O.OPCDESCR
	FROM CARRO_OPCIONAL C INNER JOIN OPCIONAL O ON C.OPCID = O.OPCID
	WHERE CARPLACA = @CARPLACA
END
--_________________________________________________________________

CREATE PROCEDURE LISTAR_LOGIN_ID
@LOGUSUAR VARCHAR(12)
AS
BEGIN 
	SELECT * FROM LOGIN_VENDEDOR
	WHERE LOGUSUAR = @LOGUSUAR
END
--_________________________________________________________________
CREATE PROCEDURE LISTAR_CLIENTE_ID
@CLICPF VARCHAR(12)
AS
BEGIN 
	SELECT * FROM CLIENTE
	WHERE CLICPF = @CLICPF
END
--_________________________________________________________________
CREATE PROCEDURE LISTAR_VENDA_ID
@VENID INT
AS
BEGIN 
	SELECT V.CLICPF, V.VENDATAV, V.VENVALOR, V.VENID, 
			C.CARPLACA, C.CARMODEL, C.CARCOR, C.CARANO,
				CLI.CLINOME, CLI.CLITELEF
	FROM VENDA V INNER JOIN CARRO C ON C.CARPLACA = V.CARPLACA
			INNER JOIN CLIENTE CLI ON V.CLICPF = CLI.CLICPF
	WHERE VENID = @VENID
END
--_________________________________________________________________
select * from carro
ALTER PROCEDURE LISTAR_CARRO_VENDIDO_ID
@CARPLACA VARCHAR(8)
AS
BEGIN 
	SELECT V.CLICPF, V.VENDATAV, V.VENVALOR, V.VENID, 
			C.CARPLACA, C.CARMODEL, C.CARCOR, C.CARANO,
			C.CARTIPO, C.CARCOMBU, C.CARMARCA,
				CLI.CLINOME, CLI.CLITELEF
	FROM VENDA V INNER JOIN CARRO C ON C.CARPLACA = V.CARPLACA
			INNER JOIN CLIENTE CLI ON V.CLICPF = CLI.CLICPF
	WHERE C.CARPLACA = @CARPLACA and C.CARSTATUS = 1
END

exeC LISTAR_CARRO_VENDIDO_ID 'VKT3247'