--TODOS COMITADOS
CREATE PROCEDURE INSERIR_OPCIONAL
@DESC VARCHAR(50)
AS
BEGIN 
	INSERT INTO OPCIONAL VALUES (@DESC)
END
--_____________________________________________________________________
CREATE PROCEDURE INSERIR_CARRO
@MODELO VARCHAR(50), @MARCA VARCHAR(20), @ANO VARCHAR(20), 
@TIPO VARCHAR(20), @COMBUSTIVEL VARCHAR(30), @COR VARCHAR(30)
AS
BEGIN 
	INSERT INTO CARRO (CARMODEL, CARMARCA, CARANO, CARTIPO, CARCOMBU, CARCOR)
	VALUES (@MODELO, @MARCA, @ANO, @TIPO, @COMBUSTIVEL, @COR)
END
--_____________________________________________________________________
CREATE PROCEDURE INSERIR_CLIENTE
@CPF VARCHAR(12), @NOME VARCHAR(75), @ENDERECO VARCHAR(75), 
@TELEFONE VARCHAR(13),@DATANASC DATE, @CIDADE VARCHAR(30)
AS
BEGIN 
	INSERT INTO CLIENTE(CLICPF, CLINOME, CLIENDER, CLITELEF, CLIDATAN, CLICIDAD)
	VALUES (@CPF, @NOME, @ENDERECO, @TELEFONE, @DATANASC, @CIDADE)
END
--________________________________________________________________________
CREATE PROCEDURE INSERIR_LOGIN
@USER VARCHAR(12), @SENHA VARCHAR(12)
AS
BEGIN 
	INSERT INTO LOGIN_VENDEDOR(LOGUSUAR, LOGSENHA)
	VALUES (@USER, @SENHA)
END
--____________________________________________________________________________
CREATE PROCEDURE INSERIR_VENDA
@CLIENTE INT, @CARRO INT, @VALOR MONEY, @DATA DATE
AS
BEGIN 
	INSERT INTO VENDA (CLICPF, CARID, VENVALOR, VENDATAV)
	VALUES (@CLIENTE, @CARRO, @VALOR, @DATA)
END